import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CustomSidebar } from "@/components/ui/CustomSidebar";
import { ProductSidebar } from "@/components/product/ProductSidebar";
import { GlobalProvider } from "@/providers/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface IProps {
	children: React.ReactNode;
	sidebar: React.ReactNode;
}

export default function RootLayout({ children, sidebar }: IProps) {
    return (
        <html lang="en">
            <GlobalProvider>
                <body className={cn(inter.className)}>
                    <CustomSidebar />

                    <div className="flex">
                        <div className="container">
                            {/* content */}
                            <div className="grow">{children}</div>
                        </div>

                        {/* sidebar slot */}
                        <div className={cn("w-[51vw]")}>
							{sidebar}
						</div>
                    </div>
                </body>
            </GlobalProvider>
        </html>
    );
}
